title: Iambadu.com
tagline: Design Portfolio Of Emmanuel Badu Sarpong
email: your-email@example.com
author: Kwabena Badu
description: >
 Web and digital designer in Italy. Focused on graphic design, brand identity and mobile-responsive, user-friendly web design.
baseurl: ''
url: 'www.iambadu.com'
image: img/grid-05.png
markdown: kramdown

  
collections:
  portfolio:
    output: true
    permalink: work/:title/

