title: Iambadu.com
tagline: Design Portfolio Of Emmanuel Badu Sarpong
email: your-email@example.com
author: Kwabena Badu
description: >
 Web and digital designer in Italy. Focused on graphic design, brand identity and mobile-responsive, user-friendly web design.
baseurl: ''
url: https://www.iambadu.github.io
image: img/grid-05.png
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-admin
  
collections:
  work:
    output: true
    permalink: work/:title/

paginate: 6
paginate_path: "/blog/page:num/"
