title: Iambadu.com
tagline: Design Portfolio Of Emmanuel Badu Sarpong
email: your-email@example.com
author: Kwabena Badu
description: >
 Verona, Italy based web and digital designer focused on graphic design, brand identity and mobile-responsive, user-friendly web design.
baseurl: ''
url: http://www.iambadu.com
image: img/grid-05.png
markdown: kramdown

  
collections:
  portfolio:
    output: true
    permalink: work/:title/

